"""Canonical role and permission catalogue.

Single source of truth for RBAC seeding. The PRD defines 10 roles; permissions are
`"<module>:<action>"`. Keep this in sync with docs/security/roles-permissions.md.
"""

from __future__ import annotations

ROLES: dict[str, str] = {
    "super_admin": "Super Admin — global platform control",
    "community_admin": "Community Admin — single-community management",
    "association_committee": "Association Committee — governance & oversight",
    "facility_manager": "Facility Manager — operations & maintenance",
    "security_supervisor": "Security Supervisor — gate security oversight",
    "security_guard": "Security Guard — live gate operations",
    "resident": "Owner / Tenant — residential unit control",
    "domestic_staff": "Domestic Staff — workforce access",
    "vendor_technician": "Vendor / Technician — service execution",
    "auditor": "Auditor — read-only compliance",
}

_MODULES = [
    "users",
    "communities",
    "residents",
    "visitors",
    "gate",
    "domestic_staff",
    "deliveries",
    "vehicles",
    "billing",
    "complaints",
    "amenities",
    "communication",
    "incidents",
    "notifications",
    "audit",
    "dashboards",
]
_ACTIONS = ["view", "create", "update", "delete", "approve", "export"]

PERMISSIONS: dict[str, str] = {
    f"{m}:{a}": f"{a.title()} {m.replace('_', ' ')}" for m in _MODULES for a in _ACTIONS
}


ROLE_PERMISSIONS: dict[str, list[str]] = {
    "super_admin": ["*"],
    "community_admin": [p for p in PERMISSIONS if not p.startswith("audit:")],
    "association_committee": [
        "billing:view",
        "billing:create",
        "billing:approve",
        "billing:export",
        "communication:view",
        "communication:create",
        "communication:update",
        "communication:approve",
        "communities:view",
        "complaints:view",
        "residents:view",
        "incidents:view",
        "dashboards:view",
        "audit:view",
        "audit:export",
        "notifications:view",
    ],
    "facility_manager": [
        "communities:view",
        "users:view",
        "users:create",
        "users:update",
        "amenities:view",
        "amenities:create",
        "amenities:update",
        "amenities:approve",
        "complaints:view",
        "complaints:create",
        "complaints:update",
        "complaints:approve",
        "complaints:export",
        "vehicles:view",
        "vehicles:update",
        "vehicles:approve",
        "incidents:view",
        "incidents:create",
        "incidents:update",
        "domestic_staff:view",
        "dashboards:view",
        "notifications:view",
    ],
    "security_supervisor": [
        "visitors:view",
        "visitors:create",
        "visitors:approve",
        "visitors:update",
        "visitors:export",
        "gate:view",
        "gate:create",
        "gate:update",
        "gate:approve",
        "gate:export",
        "domestic_staff:view",
        "domestic_staff:create",
        "domestic_staff:update",
        "deliveries:view",
        "deliveries:create",
        "deliveries:update",
        "vehicles:view",
        "vehicles:create",
        "vehicles:update",
        "incidents:view",
        "incidents:create",
        "incidents:update",
        "users:view",
        "communities:view",
        "dashboards:view",
        "notifications:view",
    ],
    "security_guard": [
        "visitors:view",
        "visitors:create",
        "visitors:update",
        "gate:view",
        "gate:create",
        "gate:update",
        "domestic_staff:view",
        "domestic_staff:create",
        "domestic_staff:update",
        "deliveries:view",
        "deliveries:create",
        "deliveries:update",
        "vehicles:view",
        "vehicles:create",
        "vehicles:update",
        "incidents:view",
        "incidents:create",
        "dashboards:view",
        "notifications:view",
    ],
    "resident": [
        "visitors:view",
        "visitors:create",
        "visitors:approve",
        "domestic_staff:view",
        "domestic_staff:create",
        "domestic_staff:update",
        "deliveries:view",
        "deliveries:create",
        "deliveries:approve",
        "deliveries:update",
        "billing:view",
        "billing:create",
        "communication:view",
        "incidents:view",
        "incidents:create",
        "dashboards:view",
        "notifications:view",
        "complaints:view",
        "complaints:create",
        "complaints:update",
        "amenities:view",
        "amenities:create",
        "amenities:update",
        "vehicles:view",
        "vehicles:create",
        "vehicles:update",
    ],
    "domestic_staff": [
        "domestic_staff:view",
        "domestic_staff:update",
        "gate:view",
        "notifications:view",
        "incidents:create",
    ],
    "vendor_technician": [
        "complaints:view",
        "complaints:update",
        "gate:view",
        "notifications:view",
    ],
    "auditor": [f"{m}:view" for m in _MODULES]
    + [
        "billing:export",
        "gate:export",
        "complaints:export",
        "visitors:export",
        "audit:view",
        "audit:export",
    ],
}
